changelog_type: 'commit_message'
header_prefix: 'Version:'
pull_request_title_regex: '(^.*v?[0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\)'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\)'
commit_changelog: true
comment_changelog: true
include_unlabeled_changes: true
group_config:
  - title: Bug Fixes
    labels:
      - hotfix
      - bug
      - bugfix
  - title: Code Improvements
    labels:
      - improvements
      - enhancement
  - title: New Features
    labels:
      - feature
      - feat
  - title: Documentation Updates
    labels:
      - docs
      - documentation
      - doc