changelog_type: 'commit_message'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: true
group_config:
  - title: Bug Fixes
    labels:
      - hotfix
      - bug
      - bugfix
  - title: Code Improvements
    labels:
      - improvements
      - enhancement
  - title: New Features
    labels:
      - feature
      - feat
  - title: Documentation Updates
    labels:
      - docs
      - documentation
      - doc